"""media uploads

Revision ID: 56a5b3493485
Revises: bbf9d73b4ff9
Create Date: 2026-08-31 19:00:33.147029

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56a5b3493485"
down_revision: str | Sequence[str] | None = "bbf9d73b4ff9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("gcs_object", sa.String(length=256), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.Enum("PENDING", "READY", "FAILED", name="media_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("bytes IS NULL OR bytes > 0", name="ck_media_bytes_positive"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gcs_object"),
    )
    op.create_index(op.f("ix_media_owner_id"), "media", ["owner_id"], unique=False)
    op.create_index(op.f("ix_media_status"), "media", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_status"), table_name="media")
    op.drop_index(op.f("ix_media_owner_id"), table_name="media")
    op.drop_table("media")
    # Postgres keeps an enum type after its last table is dropped, so without
    # this a rollback followed by a re-upgrade fails with "type already exists".
    op.execute("DROP TYPE IF EXISTS media_status")
    # ### end Alembic commands ###
