"""session revocation timestamp

Revision ID: bbf9d73b4ff9
Revises: b6f5bbf67c94
Create Date: 2026-08-30 20:48:47.933118

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bbf9d73b4ff9"
down_revision: str | Sequence[str] | None = "b6f5bbf67c94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("sessions_valid_after", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "sessions_valid_after")
    # ### end Alembic commands ###
