"""core schema: posts, recipes, social, reviews

Revision ID: fb4b9e46a7ca
Revises: 56a5b3493485
Create Date: 2026-08-31 20:05:48.982178

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fb4b9e46a7ca"
down_revision: str | Sequence[str] | None = "56a5b3493485"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Enum types this migration introduces. Postgres keeps a type after its last
# table is dropped, so the downgrade has to remove them explicitly or a re-run
# fails with "type already exists".
NEW_ENUMS = [
    "post_type",
    "post_status",
    "recipe_difficulty",
    "cook_session_kind",
    "cook_session_state",
    "cook_abandon_reason",
    "review_fidelity",
    "review_outcome",
    "instrument_level",
    "review_attribute_kind",
]


def upgrade() -> None:
    """Upgrade schema."""
    # media_status shipped with SQLAlchemy's default labelling, which uses the
    # Python member names (PENDING). Everything else — the API, the event
    # stream — speaks the lowercase values, so the same state was spelled two
    # ways depending on where you looked. Renamed here while the only rows are
    # throwaway test uploads.
    for old, new in (("PENDING", "pending"), ("READY", "ready"), ("FAILED", "failed")):
        op.execute(f"ALTER TYPE media_status RENAME VALUE '{old}' TO '{new}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_attributes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "kind", sa.Enum("jar", "cata", "modality", name="review_attribute_kind"), nullable=False
        ),
        sa.Column("slug", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "slug", name="uq_review_attribute_slug"),
    )
    op.create_table(
        "follows",
        sa.Column("follower_id", sa.UUID(), nullable=False),
        sa.Column("followee_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("follower_id <> followee_id", name="ck_follows_not_self"),
        sa.ForeignKeyConstraint(["followee_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["follower_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("follower_id", "followee_id"),
    )
    op.create_index("ix_follows_followee", "follows", ["followee_id"], unique=False)
    op.create_table(
        "posts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("discussion", "recipe", name="post_type"), nullable=False),
        sa.Column(
            "status", sa.Enum("draft", "published", "removed", name="post_status"), nullable=False
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("body_md", sa.Text(), nullable=True),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("save_count", sa.Integer(), nullable=False),
        sa.Column("vote_score", sa.Integer(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("make_again_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("wilson_lb", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("char_length(title) BETWEEN 3 AND 200", name="ck_posts_title_length"),
        sa.CheckConstraint("rating_count >= 0", name="ck_posts_rating_count_positive"),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_posts_author", "posts", ["author_id", "created_at"], unique=False)
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    op.create_index("ix_posts_feed", "posts", ["type", "status", "created_at"], unique=False)
    op.create_index(op.f("ix_posts_slug"), "posts", ["slug"], unique=False)
    op.create_index(
        "ix_posts_top",
        "posts",
        ["wilson_lb"],
        unique=False,
        postgresql_where=sa.text("status = 'published'::post_status"),
    )
    op.create_table(
        "user_reliability",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("reliability", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "instrument_level",
            sa.Enum("verdict", "report", "calibrated", name="instrument_level"),
            nullable=False,
        ),
        sa.Column("verified_cooks", sa.Integer(), nullable=False),
        sa.Column("completed_reports", sa.Integer(), nullable=False),
        sa.Column("consensus_agreement", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("jar_variance", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("scale_usage_correction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("moderation_strikes", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("reliability BETWEEN 0 AND 1", name="ck_user_reliability_range"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "comment_summaries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("summary_md", sa.Text(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("comment_count_at_generation", sa.Integer(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comment_summaries_post_id"), "comment_summaries", ["post_id"], unique=False
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("parent_comment_id", sa.UUID(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("vote_score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("char_length(body) BETWEEN 1 AND 10000", name="ck_comments_body_length"),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_comment_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_author_id"), "comments", ["author_id"], unique=False)
    op.create_index("ix_comments_parent", "comments", ["parent_comment_id"], unique=False)
    op.create_index("ix_comments_post", "comments", ["post_id", "created_at"], unique=False)
    op.create_table(
        "post_media",
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("media_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id", "media_id"),
    )
    op.create_table(
        "post_votes",
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("value IN (-1, 1)", name="ck_post_votes_value"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id", "user_id"),
    )
    op.create_table(
        "recipes",
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("yield_text", sa.String(length=120), nullable=True),
        sa.Column("prep_time_minutes", sa.Integer(), nullable=True),
        sa.Column("cook_time_minutes", sa.Integer(), nullable=True),
        sa.Column(
            "total_time_minutes",
            sa.Integer(),
            sa.Computed(
                "COALESCE(prep_time_minutes, 0) + COALESCE(cook_time_minutes, 0)", persisted=True
            ),
            nullable=True,
        ),
        sa.Column(
            "difficulty", sa.Enum("easy", "medium", "hard", name="recipe_difficulty"), nullable=True
        ),
        sa.Column("cuisine", sa.String(length=60), nullable=True),
        sa.Column(
            "dietary_tags",
            postgresql.ARRAY(sa.String(length=40)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("expected_active_minutes", sa.Integer(), nullable=True),
        sa.Column("expected_total_minutes", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "cook_time_minutes IS NULL OR cook_time_minutes >= 0", name="ck_recipes_cook_time"
        ),
        sa.CheckConstraint(
            "prep_time_minutes IS NOT NULL OR cook_time_minutes IS NOT NULL",
            name="ck_recipes_some_time_given",
        ),
        sa.CheckConstraint(
            "prep_time_minutes IS NULL OR prep_time_minutes >= 0", name="ck_recipes_prep_time"
        ),
        sa.CheckConstraint("servings >= 1", name="ck_recipes_servings"),
        sa.CheckConstraint("version >= 1", name="ck_recipes_version"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_index("ix_recipes_cuisine", "recipes", ["cuisine"], unique=False)
    op.create_index(
        "ix_recipes_dietary_tags", "recipes", ["dietary_tags"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "review_aggregates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column("pros", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cons", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("sentiment_score", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("review_count_at_generation", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_aggregates_post_id"), "review_aggregates", ["post_id"], unique=False
    )
    op.create_table(
        "saves",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("post_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    op.create_index("ix_saves_post", "saves", ["post_id"], unique=False)
    op.create_table(
        "comment_votes",
        sa.Column("comment_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("value IN (-1, 1)", name="ck_comment_votes_value"),
        sa.ForeignKeyConstraint(["comment_id"], ["comments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("comment_id", "user_id"),
    )
    op.create_table(
        "cook_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("recipe_post_id", sa.UUID(), nullable=False),
        sa.Column("recipe_version", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Enum("live", "retroactive", name="cook_session_kind"), nullable=False),
        sa.Column(
            "state",
            sa.Enum("active", "paused", "completed", "abandoned", name="cook_session_state"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active_minutes", sa.Integer(), nullable=True),
        sa.Column("timers_started", sa.Integer(), nullable=False),
        sa.Column("checklist_pct", sa.SmallInteger(), nullable=True),
        sa.Column("abandoned_at_step", sa.Integer(), nullable=True),
        sa.Column(
            "abandon_reason",
            sa.Enum(
                "ran_out_of_time",
                "missing_ingredient",
                "step_unclear",
                "technique_failed",
                "changed_plans",
                "equipment_issue",
                name="cook_abandon_reason",
            ),
            nullable=True,
        ),
        sa.Column("plausibility_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "checklist_pct IS NULL OR checklist_pct BETWEEN 0 AND 100",
            name="ck_cook_sessions_checklist_pct",
        ),
        sa.ForeignKeyConstraint(["recipe_post_id"], ["recipes.post_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_cook_sessions_user_recipe", "cook_sessions", ["user_id", "recipe_post_id"], unique=False
    )
    op.create_table(
        "recipe_ingredients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipe_post_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("group_label", sa.String(length=80), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("ingredient_name", sa.String(length=120), nullable=False),
        sa.Column("preparation_note", sa.String(length=120), nullable=True),
        sa.Column("is_optional", sa.Boolean(), nullable=False),
        sa.Column("to_taste", sa.Boolean(), nullable=False),
        sa.Column("canonical_ingredient_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("quantity IS NOT NULL OR to_taste", name="ck_ingredient_has_amount"),
        sa.CheckConstraint(
            "quantity IS NULL OR quantity > 0", name="ck_ingredient_quantity_positive"
        ),
        sa.ForeignKeyConstraint(["recipe_post_id"], ["recipes.post_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_post_id", "position", name="uq_recipe_ingredient_position"),
    )
    op.create_index(
        "ix_recipe_ingredients_recipe",
        "recipe_ingredients",
        ["recipe_post_id", "position"],
        unique=False,
    )
    op.create_table(
        "recipe_review_axes",
        sa.Column("recipe_post_id", sa.UUID(), nullable=False),
        sa.Column("attribute_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("position BETWEEN 1 AND 4", name="ck_recipe_axis_position"),
        sa.ForeignKeyConstraint(["attribute_id"], ["review_attributes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipe_post_id"], ["recipes.post_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recipe_post_id", "attribute_id"),
        sa.UniqueConstraint("recipe_post_id", "attribute_id", name="uq_recipe_axis"),
    )
    op.create_table(
        "recipe_steps",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipe_post_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("media_id", sa.UUID(), nullable=True),
        sa.CheckConstraint("char_length(instruction) >= 10", name="ck_step_instruction_length"),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recipe_post_id"], ["recipes.post_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_post_id", "position", name="uq_recipe_step_position"),
    )
    op.create_index(
        "ix_recipe_steps_recipe", "recipe_steps", ["recipe_post_id", "position"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("recipe_post_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("cook_session_id", sa.UUID(), nullable=True),
        sa.Column("recipe_version", sa.Integer(), nullable=False),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.Column("make_again", sa.Boolean(), nullable=False),
        sa.Column(
            "fidelity",
            sa.Enum("as_written", "minor_change", "major_change", name="review_fidelity"),
            nullable=False,
        ),
        sa.Column("outcome", sa.Enum("worked", "failed", name="review_outcome"), nullable=False),
        sa.Column("note", sa.String(length=280), nullable=True),
        sa.Column("photo_media_id", sa.UUID(), nullable=True),
        sa.Column("ingredient_swaps", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("overall_liking", sa.SmallInteger(), nullable=True),
        sa.Column("jar", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("execution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("modality", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "note IS NULL OR char_length(note) <= 280", name="ck_reviews_note_length"
        ),
        sa.CheckConstraint(
            "overall_liking IS NULL OR overall_liking BETWEEN 1 AND 5",
            name="ck_reviews_overall_liking",
        ),
        sa.CheckConstraint("tier IN (1, 2)", name="ck_reviews_tier"),
        sa.ForeignKeyConstraint(["cook_session_id"], ["cook_sessions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["photo_media_id"], ["media.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["recipe_post_id"], ["recipes.post_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("recipe_post_id", "user_id", name="uq_review_per_user_recipe"),
    )
    op.create_index("ix_reviews_recipe", "reviews", ["recipe_post_id", "created_at"], unique=False)
    op.create_index("ix_reviews_user", "reviews", ["user_id"], unique=False)
    op.create_table(
        "review_confidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("cook_confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("model_version", sa.String(length=16), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cook_confidence BETWEEN 0 AND 1", name="ck_review_confidence_range"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_review_confidence_current",
        "review_confidence",
        ["review_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    for old, new in (("pending", "PENDING"), ("ready", "READY"), ("failed", "FAILED")):
        op.execute(f"ALTER TYPE media_status RENAME VALUE '{old}' TO '{new}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_review_confidence_current",
        table_name="review_confidence",
        postgresql_where=sa.text("is_current"),
    )
    op.drop_table("review_confidence")
    op.drop_index("ix_reviews_user", table_name="reviews")
    op.drop_index("ix_reviews_recipe", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("ix_recipe_steps_recipe", table_name="recipe_steps")
    op.drop_table("recipe_steps")
    op.drop_table("recipe_review_axes")
    op.drop_index("ix_recipe_ingredients_recipe", table_name="recipe_ingredients")
    op.drop_table("recipe_ingredients")
    op.drop_index("ix_cook_sessions_user_recipe", table_name="cook_sessions")
    op.drop_table("cook_sessions")
    op.drop_table("comment_votes")
    op.drop_index("ix_saves_post", table_name="saves")
    op.drop_table("saves")
    op.drop_index(op.f("ix_review_aggregates_post_id"), table_name="review_aggregates")
    op.drop_table("review_aggregates")
    op.drop_index("ix_recipes_dietary_tags", table_name="recipes", postgresql_using="gin")
    op.drop_index("ix_recipes_cuisine", table_name="recipes")
    op.drop_table("recipes")
    op.drop_table("post_votes")
    op.drop_table("post_media")
    op.drop_index("ix_comments_post", table_name="comments")
    op.drop_index("ix_comments_parent", table_name="comments")
    op.drop_index(op.f("ix_comments_author_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_comment_summaries_post_id"), table_name="comment_summaries")
    op.drop_table("comment_summaries")
    op.drop_table("user_reliability")
    op.drop_index(
        "ix_posts_top",
        table_name="posts",
        postgresql_where=sa.text("status = 'published'::post_status"),
    )
    op.drop_index(op.f("ix_posts_slug"), table_name="posts")
    op.drop_index("ix_posts_feed", table_name="posts")
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.drop_index("ix_posts_author", table_name="posts")
    op.drop_table("posts")
    op.drop_index("ix_follows_followee", table_name="follows")
    op.drop_table("follows")
    op.drop_table("review_attributes")
    # ### end Alembic commands ###

    for name in NEW_ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {name}")
